/* CRIAÇÃO DA BASE DE DADOS*/
CREATE DATABASE myfinance;

/* CRIAÇÃO DAS TABELAS*/
CREATE TABLE planoconta (
ID INT IDENTITY(1,1) NOT NULL,
DESCRICAO VARCHAR(50) NOT NULL,
TIPO CHAR(1) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE transacao(
ID INT IDENTITY(1,1) NOT NULL,
DATA DATETIME NOT NULL,
VALOR DECIMAL(9,2),
HISTORICO TEXT,
planocontaid INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (planocontaid) REFERENCES planoconta(ID)
);